<?php

namespace Database\Seeders;

use Illuminate\Support\Carbon;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;

class UserGroupSeeder extends Seeder
{
    public function run()
    {
            $data = [
                    [
                        'group_name' => 'Developer',
                        'company_id' => 1,
                        'created_at' => Carbon::now(),
                        'updated_at' => Carbon::now(),
                        'status' => 2,
                    ],
                    [
                        'group_name' => 'Admin',
                        'company_id' => 2,
                        'created_at' => Carbon::now(),
                        'updated_at' => Carbon::now(),
                        'status' => 2,
                    ],
                    [
                        'name' => 'Everfirst Admin',
                        'company_id' => 2,
                        'created_at' => Carbon::now(),
                        'updated_at' => Carbon::now(),
                        'status' => 2,
                    ],
                    [
                        'name' => 'Receiving Clerk',
                        'company_id' => 1,
                        'created_at' => Carbon::now(),
                        'updated_at' => Carbon::now(),
                        'status' => 1,
                        'status' => 1,
                    ],
                    [
                        'name' => 'Calderon HR',
                        'company_id' => 1,
                        'created_at' => Carbon::now(),
                        'updated_at' => Carbon::now(),
                        'status' => 1,
                    ],
                    [
                        'name' => 'Branch Head',
                        'company_id' => 1,
                        'created_at' => Carbon::now(),
                        'updated_at' => Carbon::now(),
                        'status' => 1,
                    ],
                    [
                        'name' => 'Area Supervisor',
                        'company_id' => 1,
                        'created_at' => Carbon::now(),
                        'updated_at' => Carbon::now(),
                        'status' => 1,
                    ],
                    [
                        'name' => 'District Manager',
                        'company_id' => 1,
                        'created_at' => Carbon::now(),
                        'updated_at' => Carbon::now(),
                        'status' => 1,
                    ],
                    [
                        'name' => 'Verifier',
                        'company_id' => 1,
                        'created_at' => Carbon::now(),
                        'updated_at' => Carbon::now(),
                        'status' => 1,
                    ],
                    [
                        'name' => 'Rider',
                        'company_id' => 1,
                        'created_at' => Carbon::now(),
                        'updated_at' => Carbon::now(),
                        'status' => 1,
                    ],
                    [
                        'name' => 'Accounting Supervisor',
                        'company_id' => 1,
                        'created_at' => Carbon::now(),
                        'updated_at' => Carbon::now(),
                        'status' => 1,
                    ],
                    [
                        'name' => 'Operations Manager',
                        'company_id' => 1,
                        'created_at' => Carbon::now(),
                        'updated_at' => Carbon::now(),
                        'status' => 1,
                    ],
                    [
                        'name' => 'Treasury Head',
                        'company_id' => 1,
                        'created_at' => Carbon::now(),
                        'updated_at' => Carbon::now(),
                        'status' => 1,
                    ],
                    [
                        'name' => 'Treasury Receiving Clerk',
                        'company_id' => 1,
                        'created_at' => Carbon::now(),
                        'updated_at' => Carbon::now(),
                        'status' => 1,
                    ],
                    [
                        'name' => 'Filling Clerk',
                        'company_id' => 1,
                        'created_at' => Carbon::now(),
                        'updated_at' => Carbon::now(),
                        'status' => 1,
                    ],
                    [
                        'name' => 'Collection Receiving Clerk',
                        'company_id' => 1,
                        'created_at' => Carbon::now(),
                        'updated_at' => Carbon::now(),
                        'status' => 1,
                    ],
                    [
                        'name' => 'Auditor Assistant',
                        'company_id' => 1,
                        'created_at' => Carbon::now(),
                        'updated_at' => Carbon::now(),
                        'status' => 1,
                    ],
                    [
                        'name' => 'Treasury Assistant/Staff',
                        'company_id' => 1,
                        'created_at' => Carbon::now(),
                        'updated_at' => Carbon::now(),
                        'status' => 1,
                    ],
                    [
                        'name' => 'Approving Officer',
                        'company_id' => 1,
                        'created_at' => Carbon::now(),
                        'updated_at' => Carbon::now(),
                        'status' => 1,
                    ],
                    [
                        'name' => 'Accounting Staff',
                        'company_id' => 1,
                        'created_at' => Carbon::now(),
                        'updated_at' => Carbon::now(),
                        'status' => 1,
                    ],
                    [
                        'name' => 'Edit For new',
                        'company_id' => 1,
                        'created_at' => Carbon::now(),
                        'updated_at' => Carbon::now(),
                        'status' => 1,
                    ],
                    [
                        'name' => 'Collection Head',
                        'company_id' => 1,
                        'created_at' => Carbon::now(),
                        'updated_at' => Carbon::now(),
                        'status' => 1,
                    ],
                    [
                        'name' => 'AP/AR Staff',
                        'company_id' => 1,
                        'created_at' => Carbon::now(),
                        'updated_at' => Carbon::now(),
                        'status' => 1,
                    ],
                    [
                        'name' => 'Payroll Clerk',
                        'company_id' => 1,
                        'created_at' => Carbon::now(),
                        'updated_at' => Carbon::now(),
                        'status' => 1,
                    ],
                    [
                        'name' => 'Collection Department',
                        'company_id' => 1,
                        'created_at' => Carbon::now(),
                        'updated_at' => Carbon::now(),
                        'status' => 1,
                    ],
                    [
                        'name' => 'Chief Accounting',
                        'company_id' => 1,
                        'created_at' => Carbon::now(),
                        'updated_at' => Carbon::now(),
                        'status' => 1,
                    ],
                    [
                        'name' => 'Warehouse',
                        'company_id' => 1,
                        'created_at' => Carbon::now(),
                        'updated_at' => Carbon::now(),
                        'status' => 1,
                    ],
                    [
                        'name' => 'Accounting / Report Staff',
                        'company_id' => 1,
                        'created_at' => Carbon::now(),
                        'updated_at' => Carbon::now(),
                        'status' => 1,
                    ],
                    [
                        'name' => 'Collection Staff',
                        'company_id' => 1,
                        'created_at' => Carbon::now(),
                        'updated_at' => Carbon::now(),
                        'status' => 1,
                    ],
                    [
                        'name' => 'Collection Staff / Releasing',
                        'company_id' => 1,
                        'created_at' => Carbon::now(),
                        'updated_at' => Carbon::now(),
                        'status' => 1,
                    ],
                    [
                        'name' => 'Finance Manager',
                        'company_id' => 1,
                        'created_at' => Carbon::now(),
                        'updated_at' => Carbon::now(),
                        'status' => 1,
                    ],
                    [
                        'name' => 'Treasury Supervisor',
                        'company_id' => 1,
                        'created_at' => Carbon::now(),
                        'updated_at' => Carbon::now(),
                        'status' => 1,
                    ],
                    [
                        'name' => 'Treasury Assistant',
                        'company_id' => 1,
                        'created_at' => Carbon::now(),
                        'updated_at' => Carbon::now(),
                        'status' => 1,
                    ],
                    [
                        'name' => 'Treasury Staff',
                        'company_id' => 1,
                        'created_at' => Carbon::now(),
                        'updated_at' => Carbon::now(),
                        'status' => 1,
                    ],
                    [
                        'name' => 'Auditor Head',
                        'company_id' => 1,
                        'created_at' => Carbon::now(),
                        'updated_at' => Carbon::now(),
                        'status' => 1,
                    ],
                    [
                        'name' => 'Loan Processor',
                        'company_id' => 1,
                        'created_at' => Carbon::now(),
                        'updated_at' => Carbon::now(),
                        'status' => 1,
                    ],
                    [
                        'name' => 'General Accountant',
                        'company_id' => 1,
                        'created_at' => Carbon::now(),
                        'updated_at' => Carbon::now(),
                        'status' => 1,
                    ],
                    [
                        'name' => 'Collection / Reports Staff',
                        'company_id' => 1,
                        'created_at' => Carbon::now(),
                        'updated_at' => Carbon::now(),
                        'status' => 1,
                    ],
                    [
                        'name' => 'IT Staff',
                        'company_id' => 1,
                        'created_at' => Carbon::now(),
                        'updated_at' => Carbon::now(),
                        'status' => 1,
                    ],
                    [
                        'name' => 'Approving Head',
                        'company_id' => 1,
                        'created_at' => Carbon::now(),
                        'updated_at' => Carbon::now(),
                        'status' => 1,
                    ],
                    [
                        'name' => 'HR Manager',
                        'company_id' => 1,
                        'created_at' => Carbon::now(),
                        'updated_at' => Carbon::now(),
                        'status' => 1,
                    ],
                    [
                        'name' => 'Purchasing',
                        'company_id' => 1,
                        'created_at' => Carbon::now(),
                        'updated_at' => Carbon::now(),
                        'status' => 1,
                    ],
                    [
                        'name' => 'Treasury Rider',
                        'company_id' => 1,
                        'created_at' => Carbon::now(),
                        'updated_at' => Carbon::now(),
                        'status' => 1,
                    ],
                    [
                        'name' => 'Treasury (Multi-Line)',
                        'company_id' => 1,
                        'created_at' => Carbon::now(),
                        'updated_at' => Carbon::now(),
                        'status' => 1,
                    ],
                    [
                        'name' => 'Admin test 1 Group',
                        'company_id' => 1,
                        'created_at' => Carbon::now(),
                        'updated_at' => Carbon::now(),
                        'status' => 1,
                    ],
                    [
                        'name' => 'Admin Test 2 Group',
                        'company_id' => 1,
                        'created_at' => Carbon::now(),
                        'updated_at' => Carbon::now(),
                        'status' => 1,
                    ],
                    [
                        'name' => 'Training Manager',
                        'company_id' => 1,
                        'created_at' => Carbon::now(),
                        'updated_at' => Carbon::now(),
                        'status' => 1,
                    ],
                    [
                        'name' => 'Loan Consultant',
                        'company_id' => 1,
                        'created_at' => Carbon::now(),
                        'updated_at' => Carbon::now(),
                        'status' => 1,
                    ],
                    [
                        'name' => 'Assistant Trainer',
                        'company_id' => 1,
                        'created_at' => Carbon::now(),
                        'updated_at' => Carbon::now(),
                        'status' => 1,
                    ],

                    [
                        'name' => 'Collection Custodian',
                        'company_id' => 1,
                        'created_at' => Carbon::now(),
                        'updated_at' => Carbon::now(),
                        'status' => 1,
                    ],
                    [
                        'name' => 'Collection Supervisor',
                        'company_id' => 1,
                        'created_at' => Carbon::now(),
                        'updated_at' => Carbon::now(),
                        'status' => 1,
                    ],
                    [
                        'name' => 'Checker',
                        'company_id' => 1,
                        'created_at' => Carbon::now(),
                        'updated_at' => Carbon::now(),
                        'status' => 1,
                    ],
                    [
                        'name' => 'Passbook Custodian',
                        'company_id' => 1,
                        'created_at' => Carbon::now(),
                        'updated_at' => Carbon::now(),
                        'status' => 1,
                    ],
            ];
            DB::table('tbl_user_groups')->insert($data);
    }
}
